POST http://localhost:8000/products 
Content-Type: application/json

{
  "name": "Product 2",
  "price": 120
}

###
GET http://localhost:8000/products/99c41b5f-369f-4528-a3e4-fffd7eaffe24 HTTP/1.1

###
PUT http://localhost:8000/products/cb4e6b3d-52e0-4492-b850-e2fd8b3254b2 HTTP/1.1
Content-Type: application/json

{
  "name": "Product 2",
  "price": 114.99
}