POST http://localhost:8000/products 
Content-Type: application/json

{
  "name": "Product 4",
  "price": 99
}

###
GET http://localhost:8000/products/ecbc9dba-9fa3-48de-95b5-ee1b94f80df8 HTTP/1.1

###
GET http://localhost:8000/products/ HTTP/1.1

###
PUT http://localhost:8000/products/ecbc9dba-9fa3-48de-95b5-ee1b94f80df8 HTTP/1.1
Content-Type: application/json

{
  "name": "Product 2",
  "price": 114.99
}

###
DELETE http://localhost:8000/products/ecbc9dba-9fa3-48de-95b5-ee1b94f80df8 HTTP/1.1


